//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Masb.ExpressionTreeToJavascript
{
    public abstract class ExpressionFilterContextBuilder
    {
    	// cannot derive this class from outside: constructor is private
        private ExpressionFilterContextBuilder()
        {
        }
    
        private static ExpressionFilterContextBuilder CreateBuilder(Type componentType)
        {
    		// Activator.CreateInstance without parameters is very fast
    		// MakeGenericType is also very fast
            return (ExpressionFilterContextBuilder)Activator.CreateInstance(
    			typeof(Generic<>)
    				.MakeGenericType(componentType));
        }
    
        protected abstract ExpressionFilterContext Create(ExpressionComposer composer);
    
        public static ExpressionFilterContext Create(Type componentType, ExpressionComposer composer)
        {
            var builder = CreateBuilder(componentType);
            return builder.Create(composer);
        }
        protected abstract ExpressionFilterContext Create(CompositionContext parentContext, string componentName, object reflectedDestinationInfo);
    
        public static ExpressionFilterContext Create(Type componentType, CompositionContext parentContext, string componentName, object reflectedDestinationInfo)
        {
            var builder = CreateBuilder(componentType);
            return builder.Create(parentContext, componentName, reflectedDestinationInfo);
        }
    
        private class Generic<TComponent> : ExpressionFilterContextBuilder
        {
            protected override ExpressionFilterContext Create(ExpressionComposer composer)
            {
                return new ExpressionFilterContext<TComponent>(
    				composer);
            }
            protected override ExpressionFilterContext Create(CompositionContext parentContext, string componentName, object reflectedDestinationInfo)
            {
                return new ExpressionFilterContext<TComponent>(
    				parentContext, componentName, reflectedDestinationInfo);
            }
        }
    }
}
